export var envirotment = {
    //BASE_URL: 'https://zpos.herokuapp.com',
    //BASE_URL: 'http://18.217.143.92:3000',
    BASE_URL: 'http://66.97.38.48:3000',
    NOMBRE_USUARIO: ' ',
    NOMBRE_COMERCIO: ' ',
    RUBRO_COMERCIO: ' ',
    ID_USUARIO:'',
    COMERCIO_ID: '',
    PROVEEDOR_ID: '',
    PROVEEDOR:'',
    TOKEN:' ',
    COMERCIO_LOGIN:'',
    APIKEY: ' ',
    PEDIDO: ' ',
    PEDIDOS:' ',
    CARRITO: ' ',
    INVITACIONES: ' ',
    NEWLOGIN: ' ',
    NOMBRE_PROVEEDOR: ' ',
    RUBRO_PROVEEDOR: ' ',
    IDPUSH: ' ',
    MENSAJE_RECHAZO:' ',
    handleNotificationReceived: ' ',
    handleNotificationOpened: ' ',
    PROVEEDORES: ''
}